declare let TYPES: {
    PackageJson: symbol;
    FS: symbol;
    Glob: symbol;
    GlobFactory: symbol;
    UserMessager: symbol;
    TemplateManager: symbol;
    TemplateRunner: symbol;
    TemplateDiscoverer: symbol;
    FilePatterns: symbol;
    TransformManager: symbol;
    PathTransformManager: symbol;
    TemplateValidator: symbol;
    DefaultsAnswerer: symbol;
    HandlerService: symbol;
    i18n: symbol;
    Mapper: symbol;
    SettingsType: symbol;
    ErrorReporter: symbol;
    TemplateInfo: symbol;
    FSTreeProcessor: symbol;
    RealTreeDiscoveryHandler: symbol;
    PluginManager: symbol;
    TemplatePreprocessor: symbol;
    SearchHandlerFactory: symbol;
    Regexer: symbol;
    SimpleTransformer: symbol;
    BuiltinTransforms: symbol;
    TemplatePathUtil: symbol;
};
export default TYPES;
