let TYPES = {
    PackageJson: Symbol("package.json"),
    FS: Symbol("FileSystem"),
    Glob: Symbol("Glob"),
    GlobFactory: Symbol("GlobFactory"),
    UserMessager: Symbol("UserMessager"),
    TemplateManager: Symbol("TemplateManager"),
    TemplateRunner: Symbol("TemplateRunner"),
    TemplateDiscoverer: Symbol("TemplateDiscoverer"),
    FilePatterns: Symbol("FilePatterns"),
    TransformManager: Symbol("TransformManager"),
    PathTransformManager: Symbol("PathTransformManager"),
    TemplateValidator: Symbol("TemplateValidator"),
    DefaultsAnswerer: Symbol("DefaultsAnswerer"),
    HandlerService: Symbol("HandlerService"),
    i18n: Symbol("i18n"),
    Mapper: Symbol("Mapper"),
    SettingsType: Symbol("SettingsType"),
    ErrorReporter: Symbol("ErrorReporter"),
    TemplateInfo: Symbol("TemplateInfo"),
    FSTreeProcessor: Symbol("FSTreeProcessor"),
    RealTreeDiscoveryHandler: Symbol("RealTreeDiscoveryHandler"),
    PluginManager: Symbol("PluginManager"),
    TemplatePreprocessor: Symbol("TemplatePreprocessor"),
    SearchHandlerFactory: Symbol("SearchHandlerFactory"),
    Regexer: Symbol("Regexer"),
    SimpleTransformer: Symbol("SimpleTransformer"),
    BuiltinTransforms: Symbol("BuiltinTransforms"),
    TemplatePathUtil: Symbol("TemplatePathUtil")
}

export default TYPES;