import { IDefaultsAnswerer } from "./i-defaults-answerer";
import { injectable } from "inversify";
import { InputDef, IComplexInputDef } from "../../user-extensibility";

@injectable()
export class DefaultsAnswerer implements IDefaultsAnswerer {
    protected autoInc: number = 1;

    getDefault(def: InputDef): any {
        if ((<IComplexInputDef<any>>def).default)
        {
            return (<IComplexInputDef<any>>def).default;
        }

        return `NeomanAutogeneratedValue${(this.autoInc++).toFixed(3)}`;
    }
}